Add express example
tinyhttp/tinyws pull request #7
Opened 2021-10-20 12:07 UTC by xWTF

## Changes
This PR simply adds a working express example to `README.md`.

The example use `express.d.ts` to define `Request.ws()`, and provides a working websocket+http server snippet.

2021-12-04 02:50 UTC, xWTF commented
Any additional changes required? I've made the change as per your request, however there's no response for more than 1 month.

2021-12-22 11:10 UTC, talentlessguy requested changes

2021-12-22 11:10 UTC, talentlessguy commented on README.md
> +## Example (tinyhttp)
plz change it to this instead

```md
## Example

### tinyhttp
...

### express
...
```

2021-12-22 11:41 UTC, xWTF commented
I believe it's 1000x faster for you to push directly into my repo instead of asking for such tiny changes. I have `Allow edits by maintainers` turned on.
Anyway, new changes pushed.

2022-01-10 05:45 UTC, closed without merging

2022-12-28 17:37 UTC, mattfeury commented
not sure if this is dead in the water, but coming from express-ws, this would be really helpful to have documented.

2022-12-28 18:34 UTC, talentlessguy commented
@mattfeury pardon this disappeared in my notifications, could you please recreate the example?